### ISSUE TITLE
Logo not rendered correctly

### ISSUE THREAD

**Issue by cybre-finn** [kmein/gen-dmc#1]
Looks like this:
![rbsd](https://user-images.githubusercontent.com/20602537/85930350-e47cca00-b8bb-11ea-9d70-7c6f90b4ce6d.png)

**Comment by kmein** [comment]
Thank you for reporting this.
Which browser/OS are you on?

**Comment by cybre-finn** [comment]
I'm on Ubuntu 20.04.
Just cloned the repo and ran cabal install on the master. Maybe cabal pulled newer dependencies for me?
I discovered the web version after I opened this issue. That works fine.

**Comment by kmein** [comment]
I think it depends on the type of font you have set as "Monospace" because that's what it uses per default. If you want to use it from the command line, just try out the `--font` option.

**Comment by cybre-finn** [comment]
So it's likely to be OS dependent because Ubuntu's Monospace is the wrong one or do I have to set a specific font as param?

Anyway, feel free to close this issue if this is a wontfix. I don't depend on it, your webtool did the job perfectly.
Thank you for that.
